### ISSUE TITLE
Simplification After Clipping in Tiler

### ISSUE THREAD

**Issue by flippmoke** [thomersch/grandine#1]
It seems you are doing [simplification after clipping](https://github.com/thomersch/grandine/blob/master/cmd/tiler/tiler.go#L206-L208) and this can produce some strange artifacts often in your results from tiling. My suggested flow would be:

- Reprojection to zoom level tile coordinates 
- Simplification
- Clipping Tile (consider how this affects validity)
- Translation of coordinates to specific tile
- Encoding

**Comment by thomersch** [comment]
Good point, thanks a lot for letting me know! Totally forgot to consider this. I will look into it.
